version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    ports:
      - 9200:9200

    environment:
      - discovery.type=single-node
      # Bật chế độ bảo mật yêu cầu username, password
      - xpack.security.enabled=false
